# Generated by Django 5.2.8 on 2025-11-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.equipments')),
            ],
        ),
    ]
